### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by Uthmanbello**
In this project:
1. I deployed the repository using GitHub pages
2. I edited the web page so it will have a very good outline
3. I used linters to rid the code of errors

### CODE REVIEW

**Review by pinkmoon25 — CHANGES_REQUESTED** [review]
Hi @Uthmanbello , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
linter checks :heavy_check_mark: 
Professional Readme :heavy_check_mark: 

# Required Changes ♻️

### - [ ] Please deploy your portfolio with github pages site, you can see how to do it [here](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site), and please as the project requirements suggests add the link to your live version in the Readme file under a live demo section like this :point_down: 
image

_**currently I don't have access to the live version of your portfolio as there is no live demo section in your readme, please fix this and ask for a re-review Thanks :pray:**_ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Uthmanbello** [comment]
Hello @PinkMoon25 , 

Is it the link, uthmanbello.github.io/setup-and-mobile/, I am to put in the Live Demo part of the readme file?

**Comment by pinkmoon25** [comment]
Hi @Uthmanbello, Yes that's correct 👍

**Comment by Uthmanbello** [comment]
@PinkMoon25 This is how this part displays on my browser:

image

I use Google Chrome. It displayed differently on the browser of one of the previous code reviewers.

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
# Status: Required Changes :recycle:
Hi @Uthmanbello , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

almost-there

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

- [ ] Please, kindly update the README of your repository in the `deploy` branch and include the live demo link of your app as the previous reviewer has requested. 🤗

[Project requirements
](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md)image

- [ ] Currently, you do not have any live demo link in the `deploy` branch 👇 
image


## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Owusu-Desmond — APPROVED** [review]
Hi @Uthmanbello , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
📌 No Linters error ✅
📌 Descriptive pull request
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
